<template lang='html'>
  <Row type="flex" class="section" justify="center">
    <h1 class="sub-title">Over 400+ Data Points!</h1>


    <Col span="20">
      <div class="search-section">
        <Input
          type="text"
          icon="ios-search"
          style="width: 270px;"
          v-model="value">
        </Input>
      </div>
      <div class='search'>
        <Card>
          <p class="search-res" v-for="dataPoint in dataPointsResults">{{dataPoint}}</p>
        </Card>

      </div>

    </Col>
  </Row>
</template>

<script>
export default {
  computed: {
    dataPointsResults () {
      const vm = this
      if (vm.value === '' || !vm.value) {
        return vm.dataPoints
      } else {
        return vm.dataPoints.filter((dp) => { return dp.toLowerCase().indexOf(vm.value.toLowerCase()) > -1 })
      }
    }
  },
  data () {
    return {
      value: '',
      dataPoints: [
        '52 Week High',
        '52 Week Low',
        'Accounts Payable',
        'Accounts Payable Turnover',
        'Accounts Receivable',
        'Accounts Receivable Turnover',
        'Accrued Expenses',
        'Accrued Interest Payable',
        'Accrued Investment Income',
        'Accumulated Depreciation',
        'Accumulated Other Comprehensive Income / (Loss)',
        'Acquisitions',
        'Adjusted Close Price',
        'Adjusted High Price',
        'Adjusted Low Price',
        'Adjusted Open Price',
        'Adjusted Volume',
        'Allowance for Loan and Lease Losses',
        'Altman Z-Score',
        'Amortization Expense',
        'Amortization of Deferred Policy Acquisition Costs',
        'Ask Price',
        'Ask Size',
        'Ask Timestamp',
        'Last Price',
        'Last Size',
        'Last Timestamp',
        'Asset Retirement Reserve & Litigation Obligation',
        'Asset Turnover',
        'Augmented Payout Ratio',
        'Average Daily Volume',
        'Bankers Acceptance Outstanding',
        'Basic & Diluted Earnings per Share',
        'Basic Earnings per Share',
        'Beta',
        'Bid Price',
        'Bid Size',
        'Bid Timestamp',
        'Book Value per Share',
        'Business Address',
        'Business Phone Number',
        'Capital Expenditures (CapEx)',
        'Capital Lease Obligations',
        'Capitalized Lease Obligations Interest Expense',
        'Cash & Equivalents',
        'Cash Conversion Cycle (CCC)',
        'Cash Dividends to Common per Share',
        'Cash Income Taxes Paid',
        'Cash Interest Paid',
        'Cash Interest Received',
        'Cash Return on Invested Capital (CROIC)',
        'Change in Price',
        'Changes in Operating Assets and Liabilities, net',
        'Chief Executive Officer (CEO)',
        'Claims and Claim Expense',
        'Close Price',
        'Commitments & Contingencies',
        'Common Equity to Total Capital',
        'Common Stock',
        'Company Legal Name',
        'Company Name',
        'Company Website',
        'Compound Leverage Factor',
        'Consolidated Net Income / (Loss)',
        'Cost of Revenue to Revenue',
        'Country',
        'Current and Future Benefits',
        'Current Deferred & Payable Income Tax Liabilities',
        'Current Deferred & Refundable Income Taxes',
        'Current Deferred Revenue',
        'Current Employee Benefit Liabilities',
        'Current Ratio',
        'Current Year Forecasted Earnings Yield',
        'Customer and Other Receivables',
        'Customer Deposits',
        'Days Inventory Outstanding (DIO)',
        'Days Payable Outstanding (DPO)',
        'Days Sales Outstanding (DSO)',
        'Days to Cover',
        'Debt to Equity',
        'Debt to NOPAT',
        'Debt to Total Capital',
        'Debt-free Net Working Capital (DFNWC)',
        'Debt-free Net Working Capital to Revenue',
        'Debt-free, Cash-free Net Working Capital (DFCFNWC)',
        'Debt-free, Cash-free Net Working Capital to Revenue',
        'Deferred Acquisition Cost',
        'Depletion Expense',
        'Deposits and Money Market Investments Interest Income',
        'Deposits Interest Expense',
        'Depreciation Expense',
        'Diluted Earnings per Share',
        'Divestitures',
        'Dividend Ex Date',
        'Dividend Pay Date',
        'Dividend Payout Ratio',
        'Dividend per Share',
        'Dividend Yield',
        'Dividends Payable',
        'Earnings before Interest and Taxes (EBIT)',
        'Earnings before Interest, Taxes, Depreciation and Amortization (EBITDA)',
        'Earnings Yield',
        'EBIT Growth',
        'EBIT Less CapEx to Interest Expense',
        'EBIT Margin',
        'EBIT Q/Q Growth',
        'EBIT to Interest Expense',
        'EBITDA Growth',
        'EBITDA Margin',
        'EBITDA Q/Q Growth',
        'Effect of Exchange Rate Changes',
        'Effective Tax Rate',
        'Employee Benefit Assets',
        'Employees',
        'Enterprise Value (EV)',
        'Enterprise Value to Current Year Forecasted Revenue',
        'Enterprise Value to EBIT (EV/EBIT)',
        'Enterprise Value to EBITDA (EV/EBITDA)',
        'Enterprise Value to Free Cash Flow (EV/FCFF)',
        'Enterprise Value to Invested Capital (EV/IC)',
        'Enterprise Value to NOPAT (EV/NOPAT)',
        'Enterprise Value to Operating Cash Flow (EV/OCF)',
        'Enterprise Value to Revenue (EV/Rev)',
        'EPS Growth',
        'EPS Q/Q Growth',
        'Ex Dividend',
        'Exchange Financial Status',
        'Exploration Expense',
        'Extraordinary Income / (Loss), net',
        'Federal Funds Purchased and Securities Sold',
        'Federal Funds Purchased and Securities Sold Interest Expense',
        'Federal Funds Sold',
        'Federal Funds Sold and Securities Borrowed Interest Income',
        'Financial Leverage',
        'Five Year Average Dividend Yield',
        'Five Year Monthly Beta',
        'Five Year Weekly Beta',
        'Fixed Asset Turnover',
        'Forward Dividend Rate',
        'Forward Dividend Yield',
        'Free Cash Flow Firm Growth',
        'Free Cash Flow Firm Q/Q Growth',
        'Free Cash Flow to Firm (FCFF)',
        'Free Cash Flow to Firm to Interest Expense',
        'Future Policy Benefits',
        'Goodwill',
        'Gross Margin',
        'High Price',
        'Impairment Charge',
        'Income Tax Expense',
        'Incorporated Country',
        'Incorporated State',
        'Increase / (Decrease) in Invested Capital',
        'Industry Category',
        'Industry Group',
        'Insurance Policy Acquisition Costs',
        'Intangible Assets',
        'Interest & Investment Income',
        'Interest Bearing Deposits',
        'Interest Bearing Deposits at Other Banks',
        'Interest Burden Percent',
        'Interest Expense',
        'Inventories, net',
        'Inventory Turnover',
        'Invested Capital',
        'Invested Capital Growth',
        'Invested Capital Q/Q Growth',
        'Invested Capital Turnover',
        'Investment Banking Income',
        'Investment Securities Interest Income',
        'Issuance of Common Equity',
        'Issuance of Debt',
        'Issuance of Preferred Equity',
        'Leverage Ratio',
        'Listing Exchange',
        'Loans and Leases',
        'Loans and Leases Interest Income',
        'Loans and Leases, Net of Allowance',
        'Loans Held for Sale',
        'Loans Held for Sale, Net',
        'Long Description',
        'Long-Term Debt',
        'Long-Term Debt Interest Expense',
        'Long-Term Debt to EBITDA',
        'Long-Term Debt to Equity',
        'Long-Term Debt to NOPAT',
        'Long-Term Debt to Total Capital',
        'Long-Term Investments',
        'Low Price',
        'Mailing Address',
        'Market Capitalization',
        'Market Category',
        'Marketing Expense',
        'Mortgage Servicing Rights',
        'Net Cash From Continuing Financing Activities',
        'Net Cash From Continuing Investing Activities',
        'Net Cash From Continuing Operating Activities',
        'Net Cash From Discontinued Financing Activities',
        'Net Cash From Discontinued Investing Activities',
        'Net Cash From Discontinued Operating Activities',
        'Net Cash From Financing Activities',
        'Net Cash From Investing Activities',
        'Net Cash From Operating Activities',
        'Net Change in Cash & Equivalents',
        'Net Change in Deposits',
        'Net Debt',
        'Net Debt to EBITDA',
        'Net Debt to NOPAT',
        'Net Income / (Loss) Attributable to Common Shareholders',
        'Net Income / (Loss) Attributable to Noncontrolling Interest',
        'Net Income / (Loss) Continuing Operations',
        'Net Income / (Loss) Discontinued Operations',
        'Net Income Growth',
        'Net Income Q/Q Growth',
        'Net Increase in Fed Funds Sold',
        'Net Interest Income / (Expense)',
        'Net Nonoperating Expense (NNE)',
        'Net Nonoperating Expense Percent (NNEP)',
        'Net Nonoperating Obligations (NNO)',
        'Net Occupancy & Equipment Expense',
        'Net Operating Profit after Tax (NOPAT)',
        'Net Realized & Unrealized Capital Gains on Investments',
        'Net Working Capital (NWC)',
        'Net Working Capital to Revenue',
        'Next Year Forecasted Earnings Yield',
        'Non-Cash Adjustments To Reconcile Net Income',
        'Non-Interest Bearing Deposits',
        'Noncontrolling Interest',
        'Noncontrolling Interest Sharing Ratio',
        'Noncontrolling Interests to Total Capital',
        'Noncurrent Deferred & Payable Income Tax Liabilities',
        'Noncurrent Deferred & Refundable Income Taxes',
        'Noncurrent Deferred Revenue',
        'Noncurrent Employee Benefit Liabilities',
        'Noncurrent Note & Lease Receivables',
        'Nonoperating Income / (Expense), net',
        'NOPAT Growth',
        'NOPAT Less CapEx to Interest Expense',
        'NOPAT Margin',
        'NOPAT Q/Q Growth',
        'NOPAT to Interest Expense',
        'Normalized Net Operating Profit after Tax (NOPAT)',
        'Normalized NOPAT Margin',
        'Note & Lease Receivable',
        'One Year Monthly Beta',
        'One Year Weekly Beta',
        'Open Price',
        'Operating Cash Flow Growth',
        'Operating Cash Flow Less CapEx to Interest Expense',
        'Operating Cash Flow Q/Q Growth',
        'Operating Cash Flow to CapEx',
        'Operating Cash Flow to Interest Expense',
        'Operating Cost of Revenue',
        'Operating Expenses to Revenue',
        'Operating Margin',
        'Operating Return on Assets (OROA)',
        'Operating Revenue',
        'Other Adjustments to Consolidated Net Income / (Loss)',
        'Other Adjustments to Net Income / (Loss) Attributable to Common Shareholders)',
        'Other Assets',
        'Other Cost of Revenue',
        'Other Current Assets',
        'Other Current Liabilities',
        'Other Current Nonoperating Assets',
        'Other Current Nonoperating Liabilities',
        'Other Equity Adjustments',
        'Other Financing Activities, net',
        'Other Gains / (Losses), net',
        'Other Income / (Expense), net',
        'Other Interest Expense',
        'Other Interest Income',
        'Other Investing Activities, net',
        'Other Long-Term Liabilities',
        'Other Net Changes in Cash',
        'Other Non-Interest Income',
        'Other Noncurrent Nonoperating Assets',
        'Other Noncurrent Nonoperating Liabilities',
        'Other Noncurrent Operating Assets',
        'Other Noncurrent Operating Liabilities',
        'Other Operating Expenses / (Income)',
        'Other Revenue',
        'Other Service Charges',
        'Other Short-Term Payables',
        'Other Special Charges / (Income)',
        'Other Taxes Payable',
        'Participating Policy Holder Equity',
        'Payment of Dividends',
        'Percent Change in Price',
        'Plant, Property & Equipment, gross',
        'Plant, Property, & Equipment, net',
        'Policy Holder Funds',
        'Pre Tax Income Margin',
        'Preferred Equity to Total Capital',
        'Preferred Stock',
        'Preferred Stock Dividends Declared',
        'Premises and Equipment, Net',
        'Premiums Earned',
        'Prepaid Expenses',
        'Price Date',
        'Price Time',
        'Price to Book Value (P/BV)',
        'Price to Current Year Forecasted Earnings',
        'Price to Current Year Forecasted Revenue',
        'Price to Earnings (P/E)',
        'Price to Next Year Forecasted Earnings',
        'Price to Next Year Forecasted Revenue',
        'Price to Revenue (P/Rev)',
        'Price to Tangible Book Value (P/TBV)',
        'Profit (Net Income) Margin',
        'Property & Liability Insurance Claims',
        'Provision for Credit Losses',
        'Provision For Loan Losses',
        'Purchase of Investments',
        'Purchase of Property, Plant & Equipment',
        'Quick Ratio',
        'R&D to Revenue',
        'Redeemable Noncontrolling Interest',
        'Repayment of Debt',
        'Repurchase of Common Equity',
        'Repurchase of Preferred Equity',
        'Research & Development Expense',
        'Restricted Cash',
        'Restructuring Charge',
        'Retained Earnings',
        'Return on Assets (ROA)',
        'Return on Common Equity (ROCE)',
        'Return on Equity (ROE)',
        'Return on Invested Capital (ROIC)',
        'Return on Net Nonoperating Assets (RNNOA)',
        'Revenue Growth',
        'Revenue Q/Q Growth',
        'ROIC Less NNEP Spread (ROIC-NNEP)',
        'Salaries and Employee Benefits',
        'Sale and/or Maturity of Investments',
        'Sale of Property, Plant & Equipment',
        'SEC Centeral Index Key (CIK)',
        'Sector',
        'Security Class',
        'Security Name',
        'Security Round Lot Size',
        'Security Ticker Symbol',
        'Security Type',
        'Selling, General & Admin Expense',
        'Separate Account Business Assets',
        'Separate Account Business Liabilities',
        'Service Charges on Deposit Accounts',
        'Seven Year Monthly Beta',
        'Seven Year Weekly Beta',
        'SG&A Expenses to Revenue',
        'Short Description',
        'Short Interest',
        'Short-Term Borrowings Interest Expense',
        'Short-Term Debt',
        'Short-Term Debt to Total Capital',
        'Short-Term Investments',
        'Split Ratio',
        'Standard Industrial Classification Code (SIC)',
        'State',
        'Stock Exchange',
        'Tangible Book Value per Share',
        'Tax Burden Percent',
        'Template',
        'Ten Year Monthly Beta',
        'Ten Year Weekly Beta',
        'Three Year Monthly Beta',
        'Three Year Weekly Beta',
        'Ticker Symbol',
        'Time Deposits Placed and Other Short-Term Investments',
        'Total Assets',
        'Total Capital',
        'Total Common Equity',
        'Total Cost of Revenue',
        'Total Current Assets',
        'Total Current Liabilities',
        'Total Debt',
        'Total Depreciation and Amortization (D&A)',
        'Total Equity & Noncontrolling Interests',
        'Total Gross Profit',
        'Total Liabilities',
        'Total Liabilities & Shareholders’ Equity',
        'Total Long-Term Debt',
        'Total Non-Interest Expense',
        'Total Non-Interest Income',
        'Total Noncurrent Assets',
        'Total Noncurrent Liabilities',
        'Total Operating Expenses',
        'Total Operating Income',
        'Total Other Income / (Expense), net',
        'Total Pre-Tax Income',
        'Total Preferred & Common Equity',
        'Total Revenue',
        'Trading Account Interest Income',
        'Trading Account Securities',
        'Trailing Dividend Rate',
        'Trailing Dividend Yield',
        'Treasury Stock',
        'Trust Fees by Commissions',
        'Unearned Premiums Asset',
        'Unearned Premiums Liability',
        'Volume',
        'Weighted Average Basic & Diluted Shares Outstanding',
        'Weighted Average Basic Shares Outstanding',
        'Weighted Average Diluted Shares Outstanding'
      ]
    }
  }
}
</script>

<style lang='css' scoped>
.section {
  padding: 16px;
  height: 500px;
}

.sub-title {
    font-size: 24px;
    padding-top: 16px;
}

.sub-title-2 {
  font-size: 16px;
}

.search-section {
  padding: 16px;
}

.search-res {
  padding: 18px;
  font-size: 16px;
}
</style>
